"""subscriber Migrations

Revision ID: 376f929b090c
Revises: cfd4ca501cbe
Create Date: 2021-11-13 14:29:40.037663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376f929b090c'
down_revision = 'cfd4ca501cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
